###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{   

    "usuario": "Ramona123",
    "email": "Ramona@gmail.com",
    "contraseña": "Polola1234"

}  

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/665fa27b0051ba01d199013c HTTP/1.1

###

PUT http://localhost:9000/api/users/665fa27b0051ba01d199013c HTTP/1.1
Content-Type: application/json

{   

    "usuario": "RamonaQuesito",
    "email": "Ramona@gmail.com",
    "contraseña": "Polola1234"

}  

###

DELETE http://localhost:9000/api/users/665fa27b0051ba01d199013c HTTP/1.1


###

# Add a movie to favorites
POST http://localhost:9000/api/favorites/665fb2befd81f8988a68b832/add
Content-Type: application/json

{
  "movieId": "550"
}

###

# Remove a movie from favorites
DELETE http://localhost:3000/api/favorites/{userId}/remove/{movieId}

###

# Get all favorite movies for a user
GET http://localhost:3000/api/favorites/{userId}

###

# Get a single favorite movie for a user
GET http://localhost:3000/api/favorites/{userId}/{movieId}
